### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by perolavsvendsen**
Licensing the code

### CODE REVIEW

**Comment by perolavsvendsen** [comment]
@da-wad ref request from Matt. @bfotland I understand he had also talked to you. The repo is open and definitely needs a license. If Apache 2.0 is the right one, I'm unsure of.

**Review by ToreAad — APPROVED** [review]

**Review by da-wad — APPROVED** [review]
Necessary and sufficient.

**Comment by perolavsvendsen** [comment]
Thanks for approving, @da-wad and @ToreAad. One quick question before I merge it: The data included in the repo comes from the Volve dataset. Does it have to be explicitly stated e.g. in the readme that the license does not apply for these data?

**Comment by perolavsvendsen** [comment]
Equinor is already attributed in the present README.md which makes this compliant with the license under which the data was released. So merging this now.

**Pull request merged**
